### ISSUE TITLE
getting dispatch is not a function error

### ISSUE THREAD

**Issue by anupvarghese** [blueberryapps/redux-file-upload#11]
Do I need to connect the component separately to access the `dispatch` function? 

I have done the following
1. Imported `Fileupload` component
2. Imported `reducer` to the combine reducers

Still getting the below error on file upload.

`Uncaught TypeError: dispatch is not a function`

**Comment by jakubkottnauer** [comment]
Should be fixed in 0.0.12, thanks.

**Comment by sivanadaraja** [comment]
I am still getting the same error. I am using the version 0.0.13. is it fixed ?

 return dispatch(fileProgress.apply(undefined, [identificator].concat(args)));  -error
return dispatch(fileComplete.apply(undefined, [identificator].concat(args)));
thanks
Siva
